version: '3'

services:
  postgres:
    image: postgres:11.2-alpine
    environment:
      - POSTGRES_PASSWORD=jayoak
      - POSTGRES_USER=jayoak
      - POSTGRES_DB=jayoak
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  redis:
    image: redis:5.0.4-alpine
    command: redis-server --requirepass jayoak
    ports:
      - 6379:6379