version: '3'

services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=jayoak
      - POSTGRES_USER=jayoak
      - POSTGRES_DB=jayoak
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data